### ISSUE TITLE
on Windows, (ctrl - z) removes user interaction with app

### ISSUE THREAD

**Issue by haggerty-william** [abiosoft/ishell#18] opened 2017-02-15 16:57 UTC
When I press ctrl-z while my cmd app is in focus, all text in current line disappears including '>>>', and the window doesn't respond to key presses.

**Comment by abiosoft** [comment] 2017-02-15 17:01
@haggerty-william what is the expected behaviour ?

For me, `ctrl-z` suspends the process. And `fg` brings it back to where I was.

**Comment by abiosoft** [comment] 2017-02-15 17:01
Also, what platform are you on ?

**Comment by haggerty-william** [comment] 2017-02-15 17:02
windows

**Comment by abiosoft** [comment] 2017-02-15 17:07
Oh, good to hear that. I've been looking for testers on Windows.
What is the expected behaviour for `ctrl-z` on Windows ?

**Comment by haggerty-william** [comment] 2017-02-15 17:18
it is the 'undo' command on windows.
In my experience windows console like apps can react several different, I personally believe that some behaviors are better then others so I will document my opinion here too :)

 undo last keystroke || power-shell does this. and its wonderful!!
input "^Z"    || this is what windows cmd does. personally hate this behavior, and I dont understand why it does this.
clear line || forget where I saw this, slightly better then what windows cmd does

**Comment by cking** [comment] 2017-04-23 08:23
According to https://superuser.com/a/214261 ctrl+z doesnt undo in CLI.

The EOF char is much more correct IMO. My 2 cents

**Comment by haggerty-william** [comment] 2017-04-24 17:40
I would like to point out that no one here ever claimed that cmd interpreted ctrl+z as a undo.

Also note that the Powershell CLI(made by Microsoft) takes (shift+ctrl+z) as the EOF signal.

Opinion: 
I think having a longer shortcut for the EOF signal like the ps CLI is better because it is used significantly less then a undo functionality.
 I also don't think my opinion is that important because I never used the EOF signal to do anything before. Honestly, I cant even think of a situation where I could use a EOF signal in cmd or any cli to do something.

**Comment by abiosoft** [comment] 2017-05-30 20:10
Since there is no certainty that the behaviour is not expected, I will be closing this.

**Closed by abiosoft** 2017-05-30 20:10 UTC
Labels: discussion
